n1 = float(input('Enter the first number: '))
n2 = float(input('Enter the second number: '))
print(str(n1) + ' + ' + str(n2) + ' = ' + str(n1 + n2))
print(str(n1) + ' - ' + str(n2) + ' = ' + str(n1 - n2))
print(str(n1) + ' * ' + str(n2) + ' = ' + str(n1 * n2))
print(str(n1) + ' / ' + str(n2) + ' = ' + str(n1 // n2))
print(str(n1) + ' % ' + str(n2) + ' = ' + str(n1 % n2))
print('The average of your two numbers is ' + str((n1 + n2) / 2))
print('Goodbye!')